chapters = [
  {
    "book_id"=>"Matt",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B01___01_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B01___02_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B01___03_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B01___04_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B01___05_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B01___06_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B01___07_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B01___08_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B01___09_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B01___10_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B01___11_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B01___12_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B01___13_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>14,
    "path"=>"HNDWTCN2DA/B01___14_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>15,
    "path"=>"HNDWTCN2DA/B01___15_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>16,
    "path"=>"HNDWTCN2DA/B01___16_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>17,
    "path"=>"HNDWTCN2DA/B01___17_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>18,
    "path"=>"HNDWTCN2DA/B01___18_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>19,
    "path"=>"HNDWTCN2DA/B01___19_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>20,
    "path"=>"HNDWTCN2DA/B01___20_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>21,
    "path"=>"HNDWTCN2DA/B01___21_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>22,
    "path"=>"HNDWTCN2DA/B01___22_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>23,
    "path"=>"HNDWTCN2DA/B01___23_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>24,
    "path"=>"HNDWTCN2DA/B01___24_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>25,
    "path"=>"HNDWTCN2DA/B01___25_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>26,
    "path"=>"HNDWTCN2DA/B01___26_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>27,
    "path"=>"HNDWTCN2DA/B01___27_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Matt",
    "chapter_id"=>28,
    "path"=>"HNDWTCN2DA/B01___28_Matthew_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B02___01_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B02___02_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B02___03_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B02___04_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B02___05_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B02___06_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B02___07_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B02___08_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B02___09_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B02___10_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B02___11_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B02___12_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B02___13_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>14,
    "path"=>"HNDWTCN2DA/B02___14_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>15,
    "path"=>"HNDWTCN2DA/B02___15_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Mark",
    "chapter_id"=>16,
    "path"=>"HNDWTCN2DA/B02___16_Mark________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B03___01_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B03___02_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B03___03_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B03___04_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B03___05_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B03___06_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B03___07_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B03___08_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B03___09_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B03___10_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B03___11_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B03___12_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B03___13_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>14,
    "path"=>"HNDWTCN2DA/B03___14_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>15,
    "path"=>"HNDWTCN2DA/B03___15_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>16,
    "path"=>"HNDWTCN2DA/B03___16_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>17,
    "path"=>"HNDWTCN2DA/B03___17_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>18,
    "path"=>"HNDWTCN2DA/B03___18_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>19,
    "path"=>"HNDWTCN2DA/B03___19_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>20,
    "path"=>"HNDWTCN2DA/B03___20_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>21,
    "path"=>"HNDWTCN2DA/B03___21_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>22,
    "path"=>"HNDWTCN2DA/B03___22_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>23,
    "path"=>"HNDWTCN2DA/B03___23_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Luke",
    "chapter_id"=>24,
    "path"=>"HNDWTCN2DA/B03___24_Luke________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B04___01_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B04___02_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B04___03_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B04___04_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B04___05_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B04___06_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B04___07_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B04___08_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B04___09_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B04___10_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B04___11_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B04___12_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B04___13_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>14,
    "path"=>"HNDWTCN2DA/B04___14_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>15,
    "path"=>"HNDWTCN2DA/B04___15_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>16,
    "path"=>"HNDWTCN2DA/B04___16_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>17,
    "path"=>"HNDWTCN2DA/B04___17_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>18,
    "path"=>"HNDWTCN2DA/B04___18_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>19,
    "path"=>"HNDWTCN2DA/B04___19_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>20,
    "path"=>"HNDWTCN2DA/B04___20_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"John",
    "chapter_id"=>21,
    "path"=>"HNDWTCN2DA/B04___21_John________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B05___01_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B05___02_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B05___03_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B05___04_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B05___05_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B05___06_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B05___07_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B05___08_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B05___09_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B05___10_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B05___11_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B05___12_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B05___13_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>14,
    "path"=>"HNDWTCN2DA/B05___14_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>15,
    "path"=>"HNDWTCN2DA/B05___15_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>16,
    "path"=>"HNDWTCN2DA/B05___16_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>17,
    "path"=>"HNDWTCN2DA/B05___17_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>18,
    "path"=>"HNDWTCN2DA/B05___18_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>19,
    "path"=>"HNDWTCN2DA/B05___19_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>20,
    "path"=>"HNDWTCN2DA/B05___20_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>21,
    "path"=>"HNDWTCN2DA/B05___21_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>22,
    "path"=>"HNDWTCN2DA/B05___22_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>23,
    "path"=>"HNDWTCN2DA/B05___23_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>24,
    "path"=>"HNDWTCN2DA/B05___24_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>25,
    "path"=>"HNDWTCN2DA/B05___25_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>26,
    "path"=>"HNDWTCN2DA/B05___26_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>27,
    "path"=>"HNDWTCN2DA/B05___27_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Acts",
    "chapter_id"=>28,
    "path"=>"HNDWTCN2DA/B05___28_Acts________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B06___01_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B06___02_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B06___03_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B06___04_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B06___05_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B06___06_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B06___07_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B06___08_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B06___09_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B06___10_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B06___11_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B06___12_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B06___13_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>14,
    "path"=>"HNDWTCN2DA/B06___14_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>15,
    "path"=>"HNDWTCN2DA/B06___15_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rom",
    "chapter_id"=>16,
    "path"=>"HNDWTCN2DA/B06___16_Romans______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B07___01_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B07___02_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B07___03_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B07___04_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B07___05_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B07___06_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B07___07_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B07___08_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B07___09_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B07___10_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B07___11_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B07___12_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B07___13_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>14,
    "path"=>"HNDWTCN2DA/B07___14_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>15,
    "path"=>"HNDWTCN2DA/B07___15_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Cor",
    "chapter_id"=>16,
    "path"=>"HNDWTCN2DA/B07___16_1CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B08___01_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B08___02_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B08___03_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B08___04_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B08___05_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B08___06_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B08___07_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B08___08_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B08___09_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B08___10_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B08___11_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B08___12_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Cor",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B08___13_2CorinthiansHNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Gal",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B09___01_Galatians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Gal",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B09___02_Galatians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Gal",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B09___03_Galatians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Gal",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B09___04_Galatians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Gal",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B09___05_Galatians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Gal",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B09___06_Galatians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Eph",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B10___01_Ephesians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Eph",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B10___02_Ephesians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Eph",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B10___03_Ephesians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Eph",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B10___04_Ephesians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Eph",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B10___05_Ephesians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Eph",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B10___06_Ephesians___HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Phil",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B11___01_Philippians_HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Phil",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B11___02_Philippians_HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Phil",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B11___03_Philippians_HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Phil",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B11___04_Philippians_HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Col",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B12___01_Colossians__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Col",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B12___02_Colossians__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Col",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B12___03_Colossians__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Col",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B12___04_Colossians__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Thess",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B13___01_1Thess______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Thess",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B13___02_1Thess______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Thess",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B13___03_1Thess______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Thess",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B13___04_1Thess______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Thess",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B13___05_1Thess______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Thess",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B14___01_2Thess______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Thess",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B14___02_2Thess______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Thess",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B14___03_2Thess______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Tim",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B15___01_1Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Tim",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B15___02_1Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Tim",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B15___03_1Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Tim",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B15___04_1Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Tim",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B15___05_1Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Tim",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B15___06_1Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Tim",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B16___01_2Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Tim",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B16___02_2Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Tim",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B16___03_2Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Tim",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B16___04_2Timothy____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Titus",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B17___01_Titus_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Titus",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B17___02_Titus_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Titus",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B17___03_Titus_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Phlm",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B18___01_Philemon____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B19___01_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B19___02_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B19___03_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B19___04_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B19___05_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B19___06_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B19___07_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B19___08_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B19___09_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B19___10_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B19___11_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B19___12_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Heb",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B19___13_Hebrews_____HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Jas",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B20___01_James_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Jas",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B20___02_James_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Jas",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B20___03_James_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Jas",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B20___04_James_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Jas",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B20___05_James_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Pet",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B21___01_1Peter______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Pet",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B21___02_1Peter______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Pet",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B21___03_1Peter______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Pet",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B21___04_1Peter______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1Pet",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B21___05_1Peter______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Pet",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B22___01_2Peter______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Pet",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B22___02_2Peter______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2Pet",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B22___03_2Peter______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1John",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B23___01_1John_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1John",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B23___02_1John_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1John",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B23___03_1John_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1John",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B23___04_1John_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"1John",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B23___05_1John_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"2John",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B24___01_2John_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"3John",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B25___01_3John_______HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Jude",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B26___01_Jude________HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>1,
    "path"=>"HNDWTCN2DA/B27___01_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>2,
    "path"=>"HNDWTCN2DA/B27___02_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>3,
    "path"=>"HNDWTCN2DA/B27___03_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>4,
    "path"=>"HNDWTCN2DA/B27___04_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>5,
    "path"=>"HNDWTCN2DA/B27___05_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>6,
    "path"=>"HNDWTCN2DA/B27___06_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>7,
    "path"=>"HNDWTCN2DA/B27___07_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>8,
    "path"=>"HNDWTCN2DA/B27___08_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>9,
    "path"=>"HNDWTCN2DA/B27___09_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>10,
    "path"=>"HNDWTCN2DA/B27___10_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>11,
    "path"=>"HNDWTCN2DA/B27___11_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>12,
    "path"=>"HNDWTCN2DA/B27___12_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>13,
    "path"=>"HNDWTCN2DA/B27___13_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>14,
    "path"=>"HNDWTCN2DA/B27___14_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>15,
    "path"=>"HNDWTCN2DA/B27___15_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>16,
    "path"=>"HNDWTCN2DA/B27___16_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>17,
    "path"=>"HNDWTCN2DA/B27___17_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>18,
    "path"=>"HNDWTCN2DA/B27___18_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>19,
    "path"=>"HNDWTCN2DA/B27___19_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>20,
    "path"=>"HNDWTCN2DA/B27___20_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>21,
    "path"=>"HNDWTCN2DA/B27___21_Revelation__HNDWTCN2DA.mp3"
  },
  {
    "book_id"=>"Rev",
    "chapter_id"=>22,
    "path"=>"HNDWTCN2DA/B27___22_Revelation__HNDWTCN2DA.mp3"
  }
]
lang = Language.find_by_title("Hindi")
chapters.each do |chap|
Chapter.create(book_sid: chap["book_id"], language_id: lang.id, audio_url: chap["path"], chapter_no: chap["chapter_id"])
end